apiVersion: apps/v1
kind: Deployment
metadata:
  name: airbyte
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: airbyte-app
  template:
    metadata:
      labels:
        app: airbyte-app
    spec:
      containers:
        - image: airbyte/airbyte
          name: airbyte
          ports:
            - containerPort: 80